"""add_tunnel_config_table

Revision ID: 80f2583432cf
Revises: 1fb2802d0c86
Create Date: 2026-04-01 21:52:51.042798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f2583432cf'
down_revision: Union[str, Sequence[str], None] = '1fb2802d0c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tunnel_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('server_url', sa.String(length=255), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('verify_tls', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remote_url', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: SQLite doesn't support ALTER COLUMN, skipping tasks.direct_on_branch change
    # as it's not related to tunnel_config table creation
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tunnel_config')
    # Note: SQLite doesn't support ALTER COLUMN, skipping tasks.direct_on_branch change
    # ### end Alembic commands ###
